export const FETCH_CURRENT_USER_PENDING = 'FETCH_CURRENT_USER_PENDING'
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS'
export const FETCH_CURRENT_USER_ERROR = 'FETCH_CURRENT_USER_ERROR'

export const UPDATE_CURRENT_USER_SUCCESS = 'UPDATE_CURRENT_USER_SUCCESS'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
