export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const FETCH_CURRENT_USER_PENDING = 'FETCH_CURRENT_USER_PENDING'
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS'
export const FETCH_CURRENT_USER_ERROR = 'FETCH_CURRENT_USER_ERROR'

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
