export const FETCH_POSTS_PENDING = "FETCH_POSTS_PENDING";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";

export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";

export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";

export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";

export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";

export const SUBMIT_ANSWER_SUCCESS = "SUBMIT_ANSWER_SUCCESS";

export const APPLY_CHANNEL_FILTER = "APPLY_CHANNEL_FILTER";

export const ADD_VOTE_SUCCESS = "ADD_VOTE_SUCCESS";

export const UPDATE_VOTE_SUCCESS = "UPDATE_VOTE_SUCCESS";

export const UNDO_VOTE_SUCCESS = "UNDO_VOTE_SUCCESS";
