export default {
  FETCH_POSTS_PENDING: "FETCH_POSTS_PENDING",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_ERROR: "FETCH_POSTS_ERROR",

  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",

  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",

  SUBMIT_ANSWER_SUCCESS: "SUBMIT_ANSWER_SUCCESS",

  APPLY_CHANNEL_FILTER: "APPLY_CHANNEL_FILTER"
}
