export const FETCH_POSTS_PENDING = "FETCH_POSTS_PENDING";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";

export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";

export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
