export const VOTE_ON_POST_PENDING = "VOTE_ON_POST_PENDING";
export const VOTE_ON_POST_SUCCESS = "VOTE_ON_POST_SUCCESS";
export const VOTE_ON_POST_ERROR = "VOTE_ON_POST_ERROR";

export const UPDATE_VOTE_ON_POST_PENDING = "UPDATE_VOTE_ON_POST_PENDING";
export const UPDATE_VOTE_ON_POST_SUCCESS = "UPDATE_VOTE_ON_POST_SUCCESS";
export const UPDATE_VOTE_ON_POST_ERROR = "UPDATE_VOTE_ON_POST_ERROR";

export const UNDO_VOTE_ON_POST_PENDING = "UNDO_VOTE_ON_POST_PENDING";
export const UNDO_VOTE_ON_POST_SUCCESS = "UNDO_VOTE_ON_POST_SUCCESS";
export const UNDO_VOTE_ON_POST_ERROR = "UNDO_VOTE_ON_POST_ERROR";

export const VOTE_ON_COMMENT_PENDING = "VOTE_ON_COMMENT_PENDING"
export const VOTE_ON_COMMENT_SUCCESS = "VOTE_ON_COMMENT_SUCCESS"
export const VOTE_ON_COMMENT_ERROR = "VOTE_ON_COMMENT_ERROR"

export const UPDATE_VOTE_ON_COMMENT_PENDING = "UPDATE_VOTE_ON_COMMENT_PENDING"
export const UPDATE_VOTE_ON_COMMENT_SUCCESS = "UPDATE_VOTE_ON_COMMENT_SUCCESS"
export const UPDATE_VOTE_ON_COMMENT_ERROR = "UPDATE_VOTE_ON_COMMENT_ERROR"

export const UNDO_VOTE_ON_COMMENT_PENDING = "UNDO_VOTE_ON_COMMENT_PENDING"
export const UNDO_VOTE_ON_COMMENT_SUCCESS = "UNDO_VOTE_ON_COMMENT_SUCCESS"
export const UNDO_VOTE_ON_COMMENT_ERROR = "UNDO_VOTE_ON_COMMENT_ERROR"
